version: "3"

services:
  nginx: # Basic nginx configuration
    image: nginx:1.23.3
    ports:
      - "80:80" # HTTP port
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
  whoami: # Simple whoami container to test functionality (available via nginx at http://whoami.localhost.com)
    image: traefik/whoami
  nforwardauth: # nforwardauth example configuration
    # image: nosduco/nforwardauth:v1
    build: ../../
    environment:
      - TOKEN_SECRET=example_secret_123 # (required)
      - COOKIE_SECURE=false # Do not set cookies as secure (not recommended, and optional) (WARNING: ONLY USE IN DEV OR LAN-ONLY HOSTS)
      # - COOKIE_DOMAIN=localhost.com # Set domain for the cookies (recommended, but optional)
      # - COOKIE_NAME=nforward-auth # Set name for the cookie (optional)
      # - RATE_LIMITER_ENABLED=true # Enable or disable the built-in rate limiter
      # - RATE_LIMITER_MAX_RETRIES=3 # Max retries allowed within RATE_LIMITER_FIND_TIME
      # - RATE_LIMITER_FIND_TIME=120 # Time in seconds to keep track of login attempts
      # - RATE_LIMITER_BAN_TIME=300  # Time in seconds to ban clients after reaching RATE_LIMITER_MAX_RETRIES
      - AUTH_HOST=nforwardauth.localhost.com # (required)
      - PORT=3000
    volumes:
      - "../passwd:/passwd:ro" # Mount local passwd file at /passwd as read-only
